apiVersion: v1
kind: Service
metadata:
  name: my-ftp-service
  labels:
    app: my-ftp
spec:
  type: NodePort
  ports:
    - name: direct-port
      port: 21
      nodePort: 30021
    - name: port01
      port: 30022
      nodePort: 30022
    - name: port02
      port: 30023
      nodePort: 30023
  selector:
    app: my-ftp
