apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-ftp
spec:
  selector:
    matchLabels:
      app: my-ftp
  replicas: 1
  template:
    metadata:
      labels:
        app: my-ftp
    spec:
      volumes:
      - name: task-pv-storage
        persistentVolumeClaim:
          claimName: task-pv-claim
      containers:
      - name: my-ftp-container
#        image: fauria/vsftpd
        image: registry.cognita.ru/vsftpd:latest
        ports:
        - containerPort: 21
          protocol: TCP
          name: "ftp-server"
        volumeMounts:
        - mountPath: "/home/vsftpd"
          name: task-pv-storage
        env:
        - name: FTP_USER
          value: "user"
        - name: FTP_PASS
          value: "pass12345"
        - name: PASV_ADDRESS
          value: "192.168.95.10"
        - name: PASV_MIN_PORT
          value: "30022"
        - name: PASV_MAX_PORT
          value: "30023"
      imagePullSecrets:
      - name: regsecret
