apiVersion: v1
kind: Service
metadata:
  name: my-ftp-service
  labels:
    app: my-ftp
spec:
  type: NodePort
  ports:
    - port: 21
      nodePort: 30021
    - port: 30022
      nodePort: 30022
    - port: 30023
      nodePort: 30023
  selector:
    app: my-ftp
